package:
  name: mstm_studio
  version: 1.1.1

build:
  noarch: python
  number: 1

requirements:

  run:
    - python
about:
  summary: Python wrapper for multiple sphere T-matrix (MSTM) code and Mie theory to calculate surface plasmon resonance (SPR) spectrum and *fit* it to experiment.
