
from mstm_studio.mstm_spectrum import SPR, Material, SpheresOverlapError
# ~ from nearfield import NearField
import os   # file path operations
import datetime
import numpy as np
try:
    import matplotlib.pyplot as plt
except ImportError:
    pass

## auxilary functions to write inp file
def _float2str(f):
    return str(f).replace('e', 'd', 1)

def _complex2str(c):
    return f'({_float2str(c.real)},{_float2str(c.imag)})'

def _bool2str(b):
    if b:
        return '.true.'
    else:
        return '.false.'

def _value2str(v):
    if isinstance(v, str):
        return v
    elif isinstance(v, bool):
        return _bool2str(v)
    elif isinstance(v, complex):
        return _complex2str(v)
    else:  # float, int
        return _float2str(v)

def _list2str(vs):
    result = ''
    for v in vs:
        result = f'{result} {_value2str(v)},'
    return result
## end of auxilary functions

class SPR_v4(SPR):
    '''
    Class for calculation of surface plasmin resonance (SPR),
    running MSTM external code.
    The MSTM executable should be set in MSTM_BIN environment
    variable. Default is ~/bin/mstm_v4.x (not yet)
    '''

    paramDict = {
      'number_spheres': 0,
      'length_scale_factor': 1.0,          # 2π/λ[nm]
      'ref_index_scale_factor': 1.0+1.0j,  # multiplier for spheres
      #  'chiral_factor': 0.0+0.0j,        # chiral passive spheres
      'number_plane_boundaries': 0,        # layered environment
      'layer_ref_index': 1.0+0.0j,
      #  'medium_chiral_factor': 0.0+0.0j,
      'periodic_lattice': False,
      # 'cell_width': [3, 3],              # lattice parameters

      'mie_epsilon': 1.0E-12,           # Convergence criterion for determining the number of orders
                                        # in the Mie expansions. Negative value - number of orders.
      'translation_epsilon': 1.0E-8,    # Convergence criterion for estimating the maximum order of the cluster T matrix
      'solution_epsilon': 1.0E-8,       # Precision of linear equation system solution
      'max_iterations': 5000,           # with account of all iterations
      't_matrix_convergence_epsilon': 1.0E-6,
      #  'plane_wave_epsilon': 1E-3,       # Precision of expansion of incedent field (both for palne and gaussian waves)
      #  'iterations_per_correction': 20,  # ignored for big 'near_field_translation_distance'
      'calculate_scattering_matrix': True,
      #  'near_field_translation_distance': 1.0E6,  # can be big real, small real or negative. TWEAK FOR PERFORMANCE
      'random_orientation': False,
      # 'incidence_average': True,          # alternative way to `random_orientation` (Monte-Carlo)
      # 'number_incident_directions': 100,  # ^^
      # 'azimuthal_average' : True,
      'incident_beta_deg': 0,           # parameters for fixed orientation
      'incident_alpha_deg': 0,
      'incident_frame': True,           # scattering matrix at θ = 0 corresponds to the incident direction, and
                                        # θ = β, ϕ = 180◦ would point in the z direction in the sphere coordinate system
      'scattering_map_model': 0,        # 0 - prints the scattering matrix at discrete values of θ over a circle
                                        # 1 - prints full 2D scattering matrix
      'gaussian_beam_constant': 0,      # CB = 1/(k ω0). CB = 0 - plane wave
      'gaussian_beam_focal_point': [0.0, 0.0, 0.0],  # does not alters results for plane wave and random orientations
      # 'write_sphere_data': True,            # more data out: absorption, volume absorption efficiencies

      'output_file': 'test.dat',            # should change for each run

      'calculate_near_field': False,   # no near field calculations
      #  'calculate_t_matrix': 1,         # 1 - new calc., 0 - use old, 2 - continue calc
      #  't_matrix_file': 'tmatrix-temp.dat',
      #  'sm_number_processors': 10,      # actual number of procesors is
                                          # minimum to this value and provided by mpi
    }
    # keys that require setup at every wavelength
    local_keys = ['output_file', 'length_scale_factor',
                  'number_plane_boundaries', 'layer_ref_index',
                  't_matrix_file']

    def _write_input(self, tmpdir):
        '''
        Writes file scriptParams.inp in specified directory.
        Input:
        tmpdir -- temporaty directory to store input file
        '''
        print('Using temporary directory: %s' % tmpdir)
        outFID = open(os.path.join(tmpdir, 'scriptParams.inp'), 'w')
        outFID.write('!**********************************\n')
        outFID.write('!  MSTM input for SPR calculation\n')
        outFID.write('!  Generated by python script\n')
        outFID.write('!  %s\n' %
                     datetime.datetime.now().strftime('%Y-%m-%d %H:%M'))
        outFID.write('!**********************************\n')
        for key in self.paramDict.keys():
            if key not in self.local_keys:
                outFID.write(key + '\n')
                value = self.paramDict[key]
                if isinstance(value, list):
                    svalue = _list2str(value)
                else:
                    svalue = _value2str(value)
                outFID.write('%s \n' % svalue)

        for wl in self.wavelengths:
            k0 = 2.0 * np.pi / wl
            outFID.write('!**********************************\n')
            outFID.write('!  Wavelength  %.3f \n' % wl)
            outFID.write('!**********************************\n')
            outFID.write('output_file\n')
            outFID.write('mstm_l%.0f.out\n' % (wl * 1000))
            outFID.write('append_output_file\n')
            outFID.write('  .false.\n')
            outFID.write('length_scale_factor\n')
            outFID.write('  %.6f\n' % k0)
            outFID.write('layer_ref_index\n')
            outFID.write(f'  {_complex2str(self._environment_material.get_nk(wl))}\n')

            outFID.write('sphere_data\n')
            for i in range(len(self.spheres)):
                a = np.abs(self.spheres.a[i])  # non-negative value
                x = self.spheres.x[i]
                y = self.spheres.y[i]
                z = self.spheres.z[i]
                self.spheres.materials[i].D = 2 * a
                n = self.spheres.materials[i].get_n(wl)
                k = self.spheres.materials[i].get_k(wl)
                outFID.write('  %.4f, %.4f, %.4f, %.4f, (%.3f, %.3f) \n' %
                             (x, y, z, a, n, k))
                             # ~ (x*k0, y*k0, z*k0, a*k0, n, k))
            outFID.write('end_of_sphere_data\n')
            outFID.write('new_run\n')

        outFID.write('end_of_options\n')
        outFID.close()
        return

    def _read_output(self, tmpdir):
        if self.paramDict['random_orientation']:  # random orient.
            self.extinction = []
            self.absorbtion = []
            self.scattering = []
            for wl in self.wavelengths:
                fnl = os.path.join(tmpdir, 'mstm_l%.0f.out' % (wl * 1000))
                with open(fnl, 'r') as fout:
                    while True:
                        line = fout.readline()
                        if 'total scattering' in line: # next line after
                            break                      # required
                        elif 'total extinction, absorption, scattering efficiencies' in line:
                            values = map(float,
                                         fout.readline().strip().split())
                            values = list(values)
                            self.extinction.append(float(values[0]))
                            self.absorbtion.append(float(values[1]))
                            self.scattering.append(float(values[2]))
                # ~ os.remove(fnl)
            self.extinction = np.array(self.extinction)
            self.absorbtion = np.array(self.absorbtion)
            self.scattering = np.array(self.scattering)
            return self.wavelengths, self.extinction
        else:  # fixed orientation
            self.extinction = []  # unploraized
            self.absorbtion = []
            self.scattering = []
            self.extinction_par = []  # parallel polarization (\hat \alpha)
            self.absorbtion_par = []
            self.scattering_par = []
            self.extinction_ort = []  # perpendicular polarization (\hat \beta)
            self.absorbtion_ort = []
            self.scattering_ort = []
            for wl in self.wavelengths:
                fnl = os.path.join(tmpdir, 'mstm_l%.0f.out' % (wl * 1000))
                with open(fnl, 'r') as fout:
                    while True:
                        line = fout.readline()
                        if 'down and up hemispherical scattering efficiencies' in line:
                            break
                        elif 'total extinction, absorption, scattering efficiencies' in line:
                            values = map(float,
                                         fout.readline().strip().split())
                            values = list(values)
                            self.extinction.append(float(values[0]))
                            self.extinction_par.append(float(values[1]))
                            self.extinction_ort.append(float(values[2]))
                            self.absorbtion.append(float(values[3]))
                            self.absorbtion_par.append(float(values[4]))
                            self.absorbtion_ort.append(float(values[5]))
                            self.scattering.append(float(values[6]))
                            self.scattering_par.append(float(values[7]))
                            self.scattering_ort.append(float(values[8]))
                os.remove(fnl)
            self.extinction = np.array(self.extinction)
            self.absorbtion = np.array(self.absorbtion)
            self.scattering = np.array(self.scattering)
            self.extinction_par = np.array(self.extinction_par)
            self.absorbtion_par = np.array(self.absorbtion_par)
            self.scattering_par = np.array(self.scattering_par)
            self.extinction_ort = np.array(self.extinction_ort)
            self.absorbtion_ort = np.array(self.absorbtion_ort)
            self.scattering_ort = np.array(self.scattering_ort)
            return self.wavelengths, self.extinction

    def plot(self):
        '''
        Plot results with matplotlib.pyplot
        '''
        if self.paramDict['random_orientation']:  # random
            plt.plot(self.wavelengths, np.log(-self.extinction), 'r-', label='extinction')
        else:
            plt.plot(self.wavelengths, self.extinction_par, 'r-', label='extinction par.')
            plt.plot(self.wavelengths, self.extinction_ort, 'b-', label='extinction ort.')
            # ~ plt.plot(self.wavelengths, self.scattering_par, 'r-', label='scattering par.')
            # ~ plt.plot(self.wavelengths, self.scattering_ort, 'b-', label='scattering ort.')
            # ~ plt.plot(self.wavelengths, self.absorbtion_par, 'r-', label='scattering par.')
            # ~ plt.plot(self.wavelengths, self.absorbtion_ort, 'b-', label='scattering ort.')
        plt.legend()
        plt.show()
        return plt

    def write(self, filename):
        '''
        Save results to file
        '''
        if self.paramDict['random_orientation']:  # random
            fout = open(filename, 'w')
            fout.write('#Wavel.\tExtinct.\n')
            for i in range(len(self.wavelengths)):
                fout.write('%.4f\t%.8f\r\n' % (self.wavelengths[i],
                                               self.extinction[i]))
            fout.close()
        else:   # fixed
            fout = open(filename, 'w')
            fout.write('#Wavel.\tExt_par\tExt_ort\n')
            for i in range(len(self.wavelengths)):
                fout.write('%.4f\t%.8f\t%.8f\r\n' % (self.wavelengths[i],
                           self.extinction_par[i], self.extinction_ort[i]))
            fout.close()

    def set_incident_field(self, fixed=False, beta_angle=0.0,
                           alpha_angle=0.0, polarization_angle=0.0):
        '''
            Set incident wave orientation and polarization

            Parameters:

                fixed: bool
                    True  - fixed orientation and polarized light
                    False - average over all orientations and polarizations

                azimuth_angle, polar_angle: float (degrees)

                polarization_angle: float (degrees)
                    !sensible only for near field calculation!
                    polarization angle relative to the `k-z` palne.
                    0 - X-polarized, 90 - Y-polarized (if `azimuth` and
                    `polar` angles are zero).
        '''
        self.paramDict['random_orientation'] = not fixed
        if fixed:
            self.paramDict['incident_beta_deg'] = beta_angle
            self.paramDict['incident_alpha_deg'] = alpha_angle
            # self.paramDict['polarization_angle_deg'] = polarization_angle


if __name__ == '__main__':
    from mstm_studio.mstm_spectrum import Material, ExplicitSpheres
    mat1 = Material(os.path.join('nk', 'etaGold.txt'))
    mat2 = Material(os.path.join('nk', 'etaSilver.txt'))

    wls = np.linspace(300, 800, 100)
    # old SPR
    spr = SPR(wls, mstm_path='mstm.x', temp_dir='./temp/')
    spr.environment_material = 'air'
    spheres = ExplicitSpheres(2, [-20, 0, 0, 10, 10, 0, 0, 12],
                              mat_filename=[mat1, mat1])
    spr.set_spheres(spheres)
    # ~ spr.set_incident_field(fixed=False)
    spr.set_incident_field(fixed=True, azimuth_angle=90.0, polar_angle=90.0,
                           polarization_angle=45.0)
    spr.simulate()
    # ~ input()
    spr.write('test.dat')
    spr.plot()

    # new SPR
    spr = SPR_v4(wls, mstm_path='mstm2023.x', temp_dir='./temp/')
    spr.environment_material = 'air'
    spheres = ExplicitSpheres(2, [-20, 0, 0, 10, 10, 0, 0, 12],
                              mat_filename=[mat1, mat1])
    spr.set_spheres(spheres)
    # ~ spr.set_incident_field(fixed=False)
    spr.set_incident_field(fixed=True, beta_angle=90.0, alpha_angle=90.0,
                           polarization_angle=45.0)
    spr.simulate()
    spr.write('test.dat')
    spr.plot()

    # ~ nf = NearField(wavelength=340)
    # ~ nf.environment_material = 'glass'
    # ~ nf.set_plane(plane='xz', hmin=-10, hmax=20, vmin=-15, vmax=15, step=0.25)

    # ~ spheres = ExplicitSpheres(2, [0, 0, 0, 5, 0, 0, 11, 3],
                              # ~ mat_filename=2*[mat2])
    # ~ nf.set_spheres(spheres)
    # ~ nf.simulate()
    # ~ nf.plot()
    # ~ nf.write('nearfield.dat')

    print('See you!')
